export default {
  whiteColor: '#ffffff',
  blackColor: '#000',
  greyShadow: '#AAAAAA',
  colorGreen: '#0AB134',
  colorWhite: '#fff',
  colorViewAll: '#898989',
  borderGreen: '#2ECC71',
  colorBlue: '#1549FF',
  colorDarkBlue: '#001C7E',
  colorOrange: '#FF5E0B',
  touchSale: '#FF5E0B',
  colorRed: '#FF0000',
  colorGrayBackground: '#EDEDED',
  colorGrayText: '#676767',
  transparent: 'transparent',
};
