export default {
  iconArrowLeft: require('../assets/images/arrow-left.png'),
  background: require('../assets/images/bg.png'),
  logo: require('../assets/images/logo.png'),
  marker: require('../assets/icon/marker.png'),
  phone: require('../assets/icon/phone.png'),
  password: require('../assets/icon/password.png'),
  username: require('../assets/icon/username.png'),
  edit: require('../assets/icon/edit.png'),
  avatar: require('../assets/images/avatar.jpg'),
  infor_stadium: require('../assets/icon/infor_stadium.png'),
  profile: require('../assets/icon/profile.png'),
  service: require('../assets/icon/service.png'),
  stadium: require('../assets/icon/stadium.png'),
  statistics: require('../assets/icon/statistics.png'),
  back: require('../assets/icon/back.png'),
  pennon: require('../assets/icon/pennon.png'),
  notification: require('../assets/icon/notification.png'),
  book_close: require('../assets/icon/book_close.png'),
  book_open: require('../assets/icon/book_open.png'),
};
